name: Dairy FastAPI

on: [push, pull_request]

jobs:
  build:
    environment:
      name: test
    env:
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRES_IN: ${{secrets.ACCESS_TOKEN_EXPIRES_IN}}
      MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
      MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
      MAIL_SERVER: ${{secrets.MAIL_SERVER}}
      MAIL_PORT: ${{secrets.MAIL_PORT}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          POSTGRES_DB: ${{secrets.DATABASE_NAME}}_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Install python version 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Update pip
        run: python -m pip install --upgrade pip

      # - name: Install dependencies
      #   run: pip install -r requirements.txt

      # - name: Run tests
      #   run: pytest -v

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: deploy

    steps:
      - name: Deploy to production
        run: echo "Deploying Code to Docker"

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/dairyapi:latest
          file: ./Dockerfile

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      - name: push image to docker
        run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/dairyapi:latest
